# Generated by Django 2.0.5 on 2019-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
